datafile:
    test: 
        # - data/a0.data
        - data/a1.data
        # - data/b0.data
        - data/b1.data
        # - data/b2.data
        - data/b3.data
filter:
    locationPrefer: 0 # best = 0, avg = 1
    lower: 0.2
    upper: 0.2
